### ISSUE TITLE
The view function for 'setWallpaper' did not return a valid response.

### ISSUE THREAD

**Issue by BionicKnight** [amalthomas-exe/Dynamic-Wallpapers-Linux#2]
I'm having a problem while trying to apply the dynamic wallpaper, none worked
It installed all right, all deps satisfied.

DE: XFCE4 4.16
OS: Arch Linux

Log from terminal when run dwl and select wallpaper:

```
[pywebview] closing event is deprecated and will be removed in 4.0. Use events.closing instead
 * Serving Flask app 'main' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000 (Press CTRL+C to quit)
127.0.0.1 - - [05/May/2022 14:22:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/scripts/script.js?q=1651771364 HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/styles/style.css?q=1651771364 HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/aurora.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/beach.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/bitday.png HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/catalina.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/chihuahuan.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/cliffs.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/colony.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/desert.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/earth.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/exodus.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/factory.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/firewatch.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/forest.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/gradient.png HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/island.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/home.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/lake.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/lakeside.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/london.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/maldives.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/market.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/mojave.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/moon.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/mojave_HD.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/mountains.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/mount_fuji.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/room.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/sahara.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/seoul.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:50] "GET /static/images/street.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/bitday.png HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/tokyo.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/catalina.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/chihuahuan.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/cliffs.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/colony.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/desert.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/earth.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/factory.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/exodus.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/firewatch.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/forest.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/gradient.png HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/home.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/island.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/lakeside.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/lake.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/london.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/maldives.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/market.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/mojave.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/mountains.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/mojave_HD.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/mount_fuji.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/moon.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/room.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/sahara.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/seoul.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/tokyo.jpg HTTP/1.1" 200 -
127.0.0.1 - - [05/May/2022 14:22:51] "GET /static/images/street.jpg HTTP/1.1" 200 -
default
Inside xfce
must be privileged to use -u
must be privileged to use -u
sh: linha 1: echo: erro de escrita: Pipe quebrado
must be privileged to use -u
must be privileged to use -u
sh: linha 1: /etc/init.d/cron: Arquivo ou diretório inexistente
[2022-05-05 14:22:59,056] ERROR in app: Exception on /setWallpaper [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1526, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1545, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1701, in make_response
    raise TypeError(
TypeError: The view function for 'setWallpaper' did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [05/May/2022 14:22:59] "GET /setWallpaper?wallpaper=forest HTTP/1.1" 500
```

If you need any more info to help with this please ask, i'll provide right away, thanks in advance!

**Comment by amalthomas-exe** [comment]
@BionicKnight I see that you are using arch Linux. As of now, this app will work only on Debian/ Ubuntu based distros. However, arch support is currently under active development and would be available by this weekend.

Thank you for reporting this issue and please wait while I add arch support for the software.
