### ISSUE TITLE
Error on GNOME 43.3

### ISSUE THREAD

**Issue by zluka22** [amalthomas-exe/Dynamic-Wallpapers-Linux#8]
I'm using Fedora 37 (6.0.7-301.fc37.x86_64) GNOME 43.3
After selecting a background in web interface:
```        forest
Inside gnome
sh: line 1: crontab: command not found
sh: line 1: crontab: command not found
sh: line 1: crontab: command not found
sh: line 1: crontab: command not found
sh: line 1: /etc/init.d/cron: No such file or directory
[2023-03-02 20:08:23,359] ERROR in app: Exception on /setWallpaper [GET]
Traceback (most recent call last):
  File "/home/user/Programs/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/Programs/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/user/Programs/anaconda3/lib/python3.9/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/user/Programs/anaconda3/lib/python3.9/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
127.0.0.1 - - [02/Mar/2023 20:08:23] "GET /setWallpaper?wallpaper=firewatch HTTP/1.1" 500 -
```

**Comment by amalthomas-exe** [comment]
Is there a successful change in the wallpaper.Also comment the output of echo $DESKTOP_SESSION

**Comment by amalthomas-exe** [comment]
Is there a successful change in the desktop wallpaper.

Also what is the output of `echo $DESKTOP_SESSION`

**Comment by zluka22** [comment]
No
gnome

also i forgot to mention that i'm on wayland

**Comment by amalthomas-exe** [comment]
There is a issue with Wayland servers as of now. Will fix it
